// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: demo/v1/demo.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetHelloRequest is the request for GetHello
type GetHelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHelloRequest) Reset() {
	*x = GetHelloRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHelloRequest) ProtoMessage() {}

func (x *GetHelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHelloRequest.ProtoReflect.Descriptor instead.
func (*GetHelloRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{0}
}

func (x *GetHelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Health check messages
type CheckHealthyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: service name to check
	Service       *string `protobuf:"bytes,1,opt,name=service,proto3,oneof" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthyRequest) Reset() {
	*x = CheckHealthyRequest{}
	mi := &file_demo_v1_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthyRequest) ProtoMessage() {}

func (x *CheckHealthyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthyRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthyRequest) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{1}
}

func (x *CheckHealthyRequest) GetService() string {
	if x != nil && x.Service != nil {
		return *x.Service
	}
	return ""
}

// HealthDetails contains detailed health information for each component
type HealthDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component status: "healthy", "unhealthy", "unavailable", "not_configured"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Optional error message if component is unhealthy
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Optional latency in milliseconds
	LatencyMs     float64 `protobuf:"fixed64,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthDetails) Reset() {
	*x = HealthDetails{}
	mi := &file_demo_v1_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthDetails) ProtoMessage() {}

func (x *HealthDetails) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthDetails.ProtoReflect.Descriptor instead.
func (*HealthDetails) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{2}
}

func (x *HealthDetails) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthDetails) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HealthDetails) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

// CheckHealthyResponse contains the health status of the service
type CheckHealthyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Health status: "healthy", "degraded", "unhealthy"
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// Service name
	Service string `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	// Timestamp of the health check
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Health details for each component (database, redis, etc.)
	Details       map[string]*HealthDetails `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthyResponse) Reset() {
	*x = CheckHealthyResponse{}
	mi := &file_demo_v1_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthyResponse) ProtoMessage() {}

func (x *CheckHealthyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthyResponse.ProtoReflect.Descriptor instead.
func (*CheckHealthyResponse) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{3}
}

func (x *CheckHealthyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckHealthyResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CheckHealthyResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *CheckHealthyResponse) GetDetails() map[string]*HealthDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

// Common response structure
type Reply struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Response status code, 0 indicates success, non-zero indicates failure
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// Response message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Response data (using Struct type, can directly return JSON object)
	Data          *structpb.Struct `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reply) Reset() {
	*x = Reply{}
	mi := &file_demo_v1_demo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_demo_v1_demo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_demo_v1_demo_proto_rawDescGZIP(), []int{4}
}

func (x *Reply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Reply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Reply) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_demo_v1_demo_proto protoreflect.FileDescriptor

const file_demo_v1_demo_proto_rawDesc = "" +
	"\n" +
	"\x12demo/v1/demo.proto\x12\vapi.demo.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\"%\n" +
	"\x0fGetHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"@\n" +
	"\x13CheckHealthyRequest\x12\x1d\n" +
	"\aservice\x18\x01 \x01(\tH\x00R\aservice\x88\x01\x01B\n" +
	"\n" +
	"\b_service\"\\\n" +
	"\rHealthDetails\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x01R\tlatencyMs\"\x88\x02\n" +
	"\x14CheckHealthyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12H\n" +
	"\adetails\x18\x04 \x03(\v2..api.demo.v1.CheckHealthyResponse.DetailsEntryR\adetails\x1aV\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.api.demo.v1.HealthDetailsR\x05value:\x028\x01\"b\n" +
	"\x05Reply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data2\xc4\x01\n" +
	"\x04Demo\x12Q\n" +
	"\bGetHello\x12\x1c.api.demo.v1.GetHelloRequest\x1a\x12.api.demo.v1.Reply\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/demo/hello\x12i\n" +
	"\fCheckHealthy\x12 .api.demo.v1.CheckHealthyRequest\x1a!.api.demo.v1.CheckHealthyResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/demo/healthB7\n" +
	"\vapi.demo.v1P\x01Z&kratos-project-template/api/demo/v1;v1b\x06proto3"

var (
	file_demo_v1_demo_proto_rawDescOnce sync.Once
	file_demo_v1_demo_proto_rawDescData []byte
)

func file_demo_v1_demo_proto_rawDescGZIP() []byte {
	file_demo_v1_demo_proto_rawDescOnce.Do(func() {
		file_demo_v1_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_v1_demo_proto_rawDesc), len(file_demo_v1_demo_proto_rawDesc)))
	})
	return file_demo_v1_demo_proto_rawDescData
}

var file_demo_v1_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_demo_v1_demo_proto_goTypes = []any{
	(*GetHelloRequest)(nil),      // 0: api.demo.v1.GetHelloRequest
	(*CheckHealthyRequest)(nil),  // 1: api.demo.v1.CheckHealthyRequest
	(*HealthDetails)(nil),        // 2: api.demo.v1.HealthDetails
	(*CheckHealthyResponse)(nil), // 3: api.demo.v1.CheckHealthyResponse
	(*Reply)(nil),                // 4: api.demo.v1.Reply
	nil,                          // 5: api.demo.v1.CheckHealthyResponse.DetailsEntry
	(*structpb.Struct)(nil),      // 6: google.protobuf.Struct
}
var file_demo_v1_demo_proto_depIdxs = []int32{
	5, // 0: api.demo.v1.CheckHealthyResponse.details:type_name -> api.demo.v1.CheckHealthyResponse.DetailsEntry
	6, // 1: api.demo.v1.Reply.data:type_name -> google.protobuf.Struct
	2, // 2: api.demo.v1.CheckHealthyResponse.DetailsEntry.value:type_name -> api.demo.v1.HealthDetails
	0, // 3: api.demo.v1.Demo.GetHello:input_type -> api.demo.v1.GetHelloRequest
	1, // 4: api.demo.v1.Demo.CheckHealthy:input_type -> api.demo.v1.CheckHealthyRequest
	4, // 5: api.demo.v1.Demo.GetHello:output_type -> api.demo.v1.Reply
	3, // 6: api.demo.v1.Demo.CheckHealthy:output_type -> api.demo.v1.CheckHealthyResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_demo_v1_demo_proto_init() }
func file_demo_v1_demo_proto_init() {
	if File_demo_v1_demo_proto != nil {
		return
	}
	file_demo_v1_demo_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_v1_demo_proto_rawDesc), len(file_demo_v1_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_v1_demo_proto_goTypes,
		DependencyIndexes: file_demo_v1_demo_proto_depIdxs,
		MessageInfos:      file_demo_v1_demo_proto_msgTypes,
	}.Build()
	File_demo_v1_demo_proto = out.File
	file_demo_v1_demo_proto_goTypes = nil
	file_demo_v1_demo_proto_depIdxs = nil
}
